# Generated by Django 2.0.6 on 2018-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('ansid', models.CharField(max_length=15)),
                ('answerer', models.CharField(max_length=50)),
                ('qstnid', models.CharField(max_length=15)),
                ('pubdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.CharField(max_length=15)),
                ('question', models.CharField(max_length=500)),
                ('typeofservice', models.CharField(max_length=50)),
                ('qstnid', models.CharField(max_length=15)),
                ('asker', models.CharField(max_length=50)),
                ('pubdate', models.DateField()),
            ],
        ),
    ]
