# Generated by Django 2.0.6 on 2018-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seraddr',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicemail',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='servicephone',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='websiteurl',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
