# Generated by Django 2.0.6 on 2018-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.CharField(max_length=15)),
                ('usermail', models.CharField(max_length=15)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=500)),
            ],
        ),
    ]
